name: encaixado
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  letter_boxed_engine:
  #   path: C:/Users/lucas/Desktop/GIT clones/letter_boxed_engine
    git:
      url: https://github.com/lucas-marianno/letter_boxed_engine
      ref: main


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

